# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 6.x.x

on:
  pull_request:
    branches: [ "development", "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET 6.x.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright Browsers
      run: playwright install

    - name: Run tests
      run: dotnet test --no-build
