name: .NET 6.x.x

on:
  pull_request:
    branches: ["development", "production"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0          

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: "6.x.x"

      - name: "[run] dotnet restore"
        run: dotnet restore

      - name: "[run] dotnet build --no-restore"
        run: dotnet build --no-restore\

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet_workspace
          path: ${{ github.workspace }}
    outputs:
      dotnet_workspace: ${{ github.workspace }}

  test:
    needs: build # This ensures that the test job will only run after the build job completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: dotnet_workspace
          path: ${{ needs.build.outputs.dotnet_workspace }}

      - name: List dotnet_workspace contents '${{ needs.build.outputs.dotnet_workspace }}'
        if: always()
        run: |
          ls -al ${{ needs.build.outputs.dotnet_workspace }}

      - name: "[run] dotnet tool install --global Microsoft.Playwright.CLI"
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: "[run] playwright install"
        run: playwright install

      - name: "[run] dotnet test --no-build"
        run: dotnet test --no-build

      - name: Upload Test Assets
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-assets
          path: ${{ needs.build.outputs.dotnet_workspace }}/NUnit_E2E/bin/Debug/net6.0/assets/
