name: .NET 6.x.x

on:
  pull_request:
    branches: [ "development", "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HEADLESS: 'true'

    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
    - run: mv '/home/runner/work/DotNetE2EStarterKit/DotNetE2EStarterKit/' '/home/runner/work/DotNetE2EStarterKit/'

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '6.x.x'

    - name: "[run] dotnet restore"
      run: dotnet restore

    - name: "[run] dotnet build --no-restore"
      run: dotnet build --no-restore

  test:
    needs: build  # This ensures that the test job will only run after the build job completes successfully
    runs-on: ubuntu-latest

    env:
      HEADLESS: 'true'

    steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '6.x.x'

    - name: "[run] dotnet restore"
      run: dotnet restore

    - name: "[run] dotnet build --no-restore"
      run: dotnet build --no-restore

    - name: "[run] dotnet tool install --global Microsoft.Playwright.CLI"
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: "[run] playwright install"
      run: playwright install

    - name: "[run] dotnet test --no-build"
      run: dotnet test --no-build

    - name: List root directory contents
      if: always()
      run: |
        ls -al /home/runner/work/DotNetE2EStarterKit/NUnit_E2E/bin/Debug/net6.0/

    - name: Upload Playwright Videos
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-videos
        path: /home/runner/work/DotNetE2EStarterKit/NUnit_E2E/bin/Debug/net6.0/assets/